---
- name: ensure dependencies are installed.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ filebeat_const[ansible_os_family]['dependencies'] }}"

- name: add elastic repo for redhat
  block:
    - name: import elastic gpg key
      ansible.builtin.rpm_key:
        key: "{{ filebeat_const[ansible_os_family]['elastic_gpg'] }}"
        state: present

    - name: add elasticsearch repository
      ansible.builtin.yum_repository:
        name: "elasticsearch"
        description: "Elastic repository"
        baseurl: "{{ filebeat_const[ansible_os_family]['elastic_repo'] }}"
        gpgcheck: true
        enabled: true
        module_hotfixes: true
  when: filebeat.repo == "elastic"

- name: install filebeat
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ filebeat_const[ansible_os_family]['packages'] }}"

- name: force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true