---
- name: configure filebeat_yml
  ansible.builtin.template:
    src: "{{ filebeat_yml.src }}"
    dest: "/etc/filebeat/{{ filebeat_yml.file }}"
    owner: root
    group: root
    mode: 0644
    backup: "{{ filebeat_yml.backup }}"
  notify: restart filebeat